### PR TITLE
Moved "now" package to optionalDependencies

### PR DESCRIPTION
**Pull request by maximilize**
I don't know if this would break anything, but I guess most users don't need `now`, so let's keep it optional like `ios-deploy`.

### CODE REVIEW

**Comment by mihaiblaga89** [comment]
Moving it to `optionalDependencies` does nothing in this case. It will still install it. Optional dependencies is for packages that can be skipped, for example `ios-deploy`, which is only available on darwin arch. It's not possible to install it on windows or linux so it's 'optional'.

**Comment by pavjacko** [comment]
@maximilize yeah good point. the overall plan is so treat "now", "aws" etc deps as `integrations` type of plugins. spec for this is WIP but we can start decoupling these already

but it's not optional you need but `peerDependencies` in this case

**Comment by pavjacko** [comment]
@mihaiblaga89 I re-opened this for discussion. correct there will be diff system how to manage these type of dependencies

**Comment by mihaiblaga89** [comment]
@pavjacko roger. I would say to inject `now` or whatever package directly into the project created, not in `rnv`. Like have `rnv capabilities` / `rnv capabilities add` and if you select that you need `now` deployment, it will inject it into the project's `package.json`.

**Pull request merged**
