### PR TITLE
Fix Xiaomi MiBox detection as TV device.

### LINKED ISSUE #393: Xiaomi MiBox 3 isn't detected as a TV device.
**Describe the bug**
The Xiaomi MiBox 3 isn't detected as a TV device.

**To Reproduce**
1. Deploy hello world sample using 'rnv run -p androidtv -d' on a Xiaomi MiBox 3
2. AVD will be created even if the device is connected and ready

**Desktop (please complete the following information):**
- OS: linux x64 Ubuntu 16.04 LTS
- Node Version v10.13.0
- RNV Version v0.28.14

**Additional context**
I have a fix that I will soon submit.

### PR DESCRIPTION
**Pull request by alexandre-amalric**
This will fix #393

### CODE REVIEW

**Comment by mihaiblaga89** [comment]
@alexandre-amalric I would suggest that you use `ro.com.google.clientidbase` instead of `ro.build.host` since that is the name of the server that built the ROM. Other than that, looks good

**Comment by mihaiblaga89** [comment]
also, please change the destination branch to develop

**Comment by alexandre-amalric** [comment]
@mihaiblaga89 Done :)

**Comment by mihaiblaga89** [comment]
@alexandre-amalric perfect. Thank you!

**Comment by alexandre-amalric** [comment]
Hi @mihaiblaga89, by the way there is a better way to detect if the device is a android TV one, using features like: 

https://developer.android.com/reference/android/content/pm/PackageManager.html#FEATURE_LEANBACK

**adb shell pm list features** will return **feature:android.software.leanback** on an android TV box, not on a mobile device.

**Pull request merged**
