### PR TITLE
Unspecified ScreenOrientation Android MainActivity

### PR DESCRIPTION
**Pull request by elmpp**
## Description 

Was unable to enforce an "unspecified" screen orientation in KitchenSink through the following local `renative.json` settings:

```
    "platforms": {
        "android": {
            "enableAndroidX": true,
            "gradle.properties": {
                "android.useDeprecatedNdk": true,
                "android.enableJetifier": true,
                "android.useAndroidX": true
            },
            "AndroidManifest": {
                "children": [
                    {
                        "tag": "application",
                        "android:name": ".MainApplication",
                        "android:usesCleartextTraffic": true,
                        "android:screenOrientation": "unspecified"
                    },
                    {
                        "tag": "application",
                        "android:name": ".MainActivity",
                        "android:usesCleartextTraffic": true,
                        "android:screenOrientation": "unspecified"
                    }
                ]
            }
        },
```

Making the change within `AndroidManifest_android.json` enabled the desired behavior possible (i.e. rotate screen and screen Dimension event listeners fire ok)

## Breaking Changes

Unsure if will affect default behaviour
    
 ## I have tested my changes on:
 
 ReNative project directly:
 
* [ ] ios simulator
* [ ] ios device
* [ ] android simulator
* [ x ] android device
* [ ] web browser
* [ ] web -e next browser
* [ ] tvos simulator
* [ ] tvos device
* [ ] androidtv simulator
* [ ] androidtv device
* [ ] androidwear simulator
* [ ] androidwear device
* [ ] tizen simulator
* [ ] tizen device
* [ ] tizenmobile simulator
* [ ] tizenwatch device
* [ ] webos simulator
* [ ] webos device
* [ ] macos 
* [ ] windows
* [ ] chromecast device

New project:
 
* [ ] ios simulator
* [ ] ios device
* [ ] android simulator
* [ ] android device
* [ ] web browser
* [ ] web -e next browser
* [ ] tvos simulator
* [ ] tvos device
* [ ] androidtv simulator
* [ ] androidtv device
* [ ] androidwear simulator
* [ ] androidwear device
* [ ] tizen simulator
* [ ] tizen device
* [ ] tizenmobile simulator
* [ ] tizenwatch device
* [ ] webos simulator
* [ ] webos device
* [ ] macos 
* [ ] windows
* [ ] chromecast device

Existing Project created with previous version of renative:
 
* [ ] ios simulator
* [ ] ios device
* [ x ] android simulator
* [ ] android device
* [ ] web browser
* [ ] web -e next browser
* [ ] tvos simulator
* [ ] tvos device
* [ ] androidtv simulator
* [ ] androidtv device
* [ ] androidwear simulator
* [ ] androidwear device
* [ ] tizen simulator
* [ ] tizen device
* [ ] tizenmobile simulator
* [ ] tizenwatch device
* [ ] webos simulator
* [ ] webos device
* [ ] macos 
* [ ] windows
* [ ] chromecast device

### CODE REVIEW

**Comment by pavjacko** [comment]
@elmpp you are not targeting correct tag in your manifest.

If you check the docs the docs:

https://renative.org/docs/next/api-config#androidmanifest

`IMPORTANT: always ensure that your object contains tag and android:name to target correct tag to merge into`

In android manifest activity is always a child tag (NOT sibling) of an application tag thus your config should look like:

```
"platforms": {
        "android": {
            "enableAndroidX": true,
            "gradle.properties": {
                "android.useDeprecatedNdk": true,
                "android.enableJetifier": true,
                "android.useAndroidX": true
            },
            "AndroidManifest": {
                "children": [
                    {
                        "tag": "application",
                        "android:name": ".MainApplication",
                        "android:usesCleartextTraffic": true,
                        "children": [
                            {
                                "tag": "application",
                                "android:name": ".MainActivity",
                                "android:screenOrientation": "unspecified"
                            }
                        ]
                    }
                ]
            }
        },
```

also don't forget you might have multiple native activities configured in your project. ie for SplashActivity you would do the same:

```
 {
       "tag": "application",
       "android:name": ".SplashActivity",
       "android:screenOrientation": "unspecified"
 }
```
etc..

I recommend to always cross-check generated build files `platformsBuilds/...` to help with debugging

closing this PR as it's not valid

**Comment by elmpp** [comment]
ok thanks

**Comment by elmpp** [comment]
this is what worked in the end:

```
"AndroidManifest": {
                "children": [
                    {
                        "tag": "application",
                        "android:name": ".MainApplication",
                        "android:usesCleartextTraffic": true,
                        "children": [
                            {
                                "tag": "activity",
                                "android:name": ".MainActivity",
                                "android:screenOrientation": "unspecified"
                            }
                        ]
                    }
                ]
            }
        },
```

**Comment by pavjacko** [comment]
good catch. activity instead of application is correct 👍  . updated comment above

**Pull request closed without merging**
